name: neo
description: GPSTech App in Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  clipboard: ^0.1.3
  dio: ^4.0.6
  dropdown_search: ^5.0.5
  email_validator: ^2.0.1
  flextras: ^1.0.0
  fluent_ui: ^4.3.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_markdown: ^0.6.10+5
  flutter_riverpod: ^2.1.3
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  hive: ^2.2.3
  numberpicker: ^2.1.1
  path_provider: ^2.0.11
  searchable_paginated_dropdown: ^0.0.7
  spflutter_number_picker: ^1.4.2
  syncfusion_flutter_core: ^20.4.43
  syncfusion_flutter_datagrid: ^20.4.43
  system_theme: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0
  window_manager: ^0.2.7

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#42a5f5"
  image: web/assets/flutter_logo.png
